project_name: 'byol-a-2'
# Unit duration in seconds for one audio segment.
unit_sec: 0.25
# FFT parameters.
sample_rate: 48000
n_fft: 1024
win_length: 1024
hop_length: 160
n_mels: 64
f_min: 20
f_max: 22000
# Dimensions of feature representations.
feature_d: 2048
# BYOL parameters.
proj_size: 256
proj_dim: 4096
ema_decay: 0.99
# Training parameters.
seed: 42
batch_size: 32
lr: 0.0003
epochs: 10000
gpus: 8
num_workers: 8
# Weight pathname for resuming training.
resume: 
# Shape of log-mel spectrogram [Frequency bins, Time bins].
shape: [64, 96]
# Folder to store trained weight files.
checkpoint_folder: checkpoints
# Folder containing the preprocessed training data
audio_dir: ../preprocessed